// Mock data for UI development — replace with real DB calls later

export const mockUser = {
  id: 'user_01',
  name: 'Daryl',
  email: 'daryl@example.com',
  tier: 'FREE' as const,
  goals: ['Manage anxiety', 'Sleep better', 'Build self-awareness'],
  reminderTime: '21:00',
  reminderFreq: 'daily',
  weeklySummary: null,
  createdAt: new Date('2025-12-01'),
}

export const mockStreak = {
  current: 7,
  longest: 23,
  shields: 2,
  lastEntry: new Date(),
}

export const mockBadges = [
  { key: 'first_entry', name: 'First Words', description: 'Wrote your first entry', iconEmoji: '✍️', earned: true, earnedAt: new Date('2025-12-01') },
  { key: 'streak_7',   name: 'Week Warrior', description: '7-day streak', iconEmoji: '🔥', earned: true, earnedAt: new Date('2026-01-10') },
  { key: 'streak_30',  name: 'Month Mind',   description: '30-day streak', iconEmoji: '🌙', earned: false, earnedAt: null },
  { key: 'entries_10', name: 'Ten Deep',     description: 'Wrote 10 entries', iconEmoji: '📖', earned: true, earnedAt: new Date('2026-01-15') },
  { key: 'entries_50', name: 'Half Century', description: 'Wrote 50 entries', iconEmoji: '🏆', earned: false, earnedAt: null },
  { key: 'mood_log',   name: 'Mood Mapper',  description: 'Logged mood 7 days in a row', iconEmoji: '🎨', earned: false, earnedAt: null },
]

export const mockPrompt = {
  id: 'prompt_today',
  text: "What's one small thing that went better than expected today?",
  category: 'Gratitude',
}

export const mockEntries = [
  // Week 1 (most recent)
  {
    id: 'entry_01',
    title: 'Quieter morning',
    body: `I woke up before my alarm today, which never happens. Lay there for a few minutes just listening. The birds were already at it — some kind of argument in the oak tree. It sounds ridiculous but it made me smile.\n\nI've been trying not to check my phone first thing. It's harder than I thought. The pull is automatic. But this morning I managed it, made coffee, and just sat. Not meditating, just sitting. No agenda.\n\nAnxiety is usually loudest in the morning and today it felt quieter. Not gone, just... further away. Like it was in the next room instead of in my chest.`,
    moodScore: 72,
    moodLabel: 'Calm',
    wordCount: 112,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Positive morning experience with reduced anxiety. Notable progress with phone habits and intentional stillness.',
    aiFlags: [],
    createdAt: new Date('2026-03-27T08:14:00'),
  },
  {
    id: 'entry_02',
    title: null,
    body: `Rough day. Meeting didn't go well and I can feel myself spiralling into the usual loop — what did I say wrong, what do they think of me, should I have prepared more. I know the pattern. Knowing doesn't stop it.\n\nTook a walk at lunch which helped a bit. Put headphones on and just walked without a destination for 20 minutes. Felt human again by the time I got back.`,
    moodScore: 38,
    moodLabel: 'Anxious',
    wordCount: 74,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Difficult day with social anxiety triggers at work. Positive coping with physical movement.',
    aiFlags: ['rumination'],
    createdAt: new Date('2026-03-26T19:43:00'),
  },
  {
    id: 'entry_03',
    title: 'Something shifted',
    body: `Hard to explain but I feel like something shifted today. Had lunch with my sister for the first time in months. We talked — actually talked — for two hours. No awkwardness, no walking on eggshells. I'd forgotten what that felt like.\n\nShe said something that stuck with me: "You seem more like yourself lately." I didn't know what to say. I'm not sure what version of myself I've been, but maybe this one is closer to the real one.`,
    moodScore: 81,
    moodLabel: 'Connected',
    wordCount: 95,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Strong sense of reconnection and authentic self. Meaningful social interaction with family.',
    aiFlags: [],
    createdAt: new Date('2026-03-25T15:22:00'),
  },
  {
    id: 'entry_04',
    title: "Couldn't sleep",
    body: `Up at 3am again. Lay there for an hour before giving up. Made tea, sat by the window. The street is so different at night — emptier and somehow more honest.\n\nMind was doing its thing. Old conversations, imagined futures, worst-case scenarios. I tried the breathing thing my therapist suggested. 4-7-8. It didn't knock me out but it took the edge off enough that I eventually drifted back around 5.`,
    moodScore: 44,
    moodLabel: 'Unsettled',
    wordCount: 88,
    isPrivate: true,
    sharedWithTherapist: false,
    aiSummary: 'Sleep disruption with racing thoughts. Positive: actively using coping technique (4-7-8 breathing).',
    aiFlags: ['sleep-issues'],
    createdAt: new Date('2026-03-24T03:47:00'),
  },
  {
    id: 'entry_05',
    title: 'Weekend',
    body: `Did almost nothing today and felt guilty about it for most of the morning. Eventually gave myself permission to just be. Read for three hours. Cooked a proper meal. Watched two episodes of something I've been putting off.\n\nWhy is rest so hard to accept? I work five days a week, I earned this. But the guilt was there anyway, like an uninvited guest at a dinner party — just sitting there, not saying anything, ruining the vibe.`,
    moodScore: 61,
    moodLabel: 'Mixed',
    wordCount: 91,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Difficulty with rest and self-permission. Good awareness of guilt pattern. Self-care activities present.',
    aiFlags: [],
    createdAt: new Date('2026-03-22T17:05:00'),
  },
  // Week 2
  {
    id: 'entry_06',
    title: 'Therapy today',
    body: `Good session. We talked about the pattern I keep falling into — the way I shrink in group settings but then feel resentful about not being heard. She pointed out that those two things are connected. Obviously. But somehow I needed to hear it out loud.`,
    moodScore: 68,
    moodLabel: 'Reflective',
    wordCount: 52,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Productive therapy session with insight into social behaviour patterns.',
    aiFlags: [],
    createdAt: new Date('2026-03-21T17:30:00'),
  },
  {
    id: 'entry_07',
    title: null,
    body: `Just writing because I said I would. Nothing to report. Day was fine, nothing memorable. Sometimes that's enough.`,
    moodScore: 58,
    moodLabel: 'Okay',
    wordCount: 24,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-20T21:05:00'),
  },
  {
    id: 'entry_08',
    title: 'Bad spiral',
    body: `Stayed in bed until noon. Not because I was tired — I wasn't. Just didn't want to face the day. Eventually got up, made coffee, and sat staring out the window for what felt like an hour.\n\nThis is the thing I find hardest to explain. It's not sadness exactly. More like being weighed down by nothing in particular.`,
    moodScore: 28,
    moodLabel: 'Low',
    wordCount: 67,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Low energy day with signs of low mood and motivation difficulty. Recommended monitoring.',
    aiFlags: ['low-mood'],
    createdAt: new Date('2026-03-19T14:22:00'),
  },
  {
    id: 'entry_09',
    title: 'Better than yesterday',
    body: `Woke up earlier, which helped. Made myself go for a run — first one in two weeks. Only 20 minutes but my body remembered how to do it. Endorphins are real, it turns out.\n\nFeeling cautiously okay. Trying not to make too much of a good day in case tomorrow is bad again.`,
    moodScore: 65,
    moodLabel: 'Alright',
    wordCount: 60,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Mood recovery with physical exercise. Some resilience concerns noted around anticipatory anxiety.',
    aiFlags: [],
    createdAt: new Date('2026-03-18T09:45:00'),
  },
  {
    id: 'entry_10',
    title: 'Sunday afternoon',
    body: `Rainy day. Stayed in and read. Called mum — she sounded good, which always settles something in me. We talked for an hour about nothing important. Sometimes that's exactly what's needed.`,
    moodScore: 74,
    moodLabel: 'Calm',
    wordCount: 44,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-16T15:10:00'),
  },
  // Week 3
  {
    id: 'entry_11',
    title: 'Overwhelmed',
    body: `Too much going on. Work is piling up and I can't seem to prioritise anything. Every time I sit down to focus on one thing, I think about three others I should be doing instead.\n\nI know this is a thinking problem more than a time problem. Still feels like a time problem.`,
    moodScore: 35,
    moodLabel: 'Anxious',
    wordCount: 55,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Work-related overwhelm with difficulty prioritising. Classic anxiety-driven cognitive pattern.',
    aiFlags: ['rumination'],
    createdAt: new Date('2026-03-14T20:55:00'),
  },
  {
    id: 'entry_12',
    title: 'Lunch with a friend',
    body: `Really needed that. We've been saying we'd catch up for months and finally did it. He's doing well — new job, seems settled. I felt genuinely happy for him instead of the usual pang of comparison. Progress.`,
    moodScore: 78,
    moodLabel: 'Good',
    wordCount: 47,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-13T14:00:00'),
  },
  {
    id: 'entry_13',
    title: null,
    body: `Tired. Not sleeping well this week. Keep waking up around 4 and lying there for an hour. Starting to dread bedtime.`,
    moodScore: 41,
    moodLabel: 'Unsettled',
    wordCount: 27,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Persistent sleep disturbance noted. Dread of bedtime is a concerning pattern worth addressing.',
    aiFlags: ['sleep-issues'],
    createdAt: new Date('2026-03-12T22:15:00'),
  },
  {
    id: 'entry_14',
    title: 'Clarity',
    body: `Something clicked today during a meeting. I realised I'd been trying to solve a problem I didn't actually care about. Spent ten minutes afterwards just sitting with that thought. Felt lighter for most of the afternoon.`,
    moodScore: 76,
    moodLabel: 'Good',
    wordCount: 46,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-11T16:45:00'),
  },
  {
    id: 'entry_15',
    title: 'Good morning',
    body: `Slept well. First time in about a week. Everything feels more manageable today. Funny how sleep is the entire ballgame.`,
    moodScore: 82,
    moodLabel: 'Great',
    wordCount: 27,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-10T08:30:00'),
  },
  // Week 4
  {
    id: 'entry_16',
    title: null,
    body: `Hard day. Nothing specific went wrong but I felt irritable and flat from morning onwards. Snapped at a colleague over something trivial and felt terrible about it for hours.`,
    moodScore: 33,
    moodLabel: 'Low',
    wordCount: 38,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Irritability and flat mood. Guilt after interpersonal conflict suggests strong empathy but also rumination risk.',
    aiFlags: ['low-mood'],
    createdAt: new Date('2026-03-08T21:10:00'),
  },
  {
    id: 'entry_17',
    title: 'Walked home',
    body: `Decided to walk home from work instead of getting the bus. About 45 minutes. By the time I got back I'd completely forgotten what I'd been anxious about. Worth remembering.`,
    moodScore: 70,
    moodLabel: 'Calm',
    wordCount: 37,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-07T18:50:00'),
  },
  {
    id: 'entry_18',
    title: 'Morning pages',
    body: `Tried writing first thing before I looked at my phone. Three pages of stream of consciousness. Most of it was nonsense but at the end there was something real buried in there about what I actually want from the next year. Worth doing again.`,
    moodScore: 73,
    moodLabel: 'Calm',
    wordCount: 52,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-06T07:20:00'),
  },
  {
    id: 'entry_19',
    title: 'Hard conversation',
    body: `Had the talk I've been putting off. It went better than I feared but worse than I hoped. At least it happened. The relief of not having to dread it anymore outweighs the discomfort of having done it.`,
    moodScore: 55,
    moodLabel: 'Mixed',
    wordCount: 44,
    isPrivate: true,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-05T20:00:00'),
  },
  {
    id: 'entry_20',
    title: null,
    body: `Really good day. Can't remember the last time I said that and meant it. Woke up with energy, the work I'd been stuck on suddenly made sense, and I finished the day feeling like myself. Just noting it down so I remember it exists.`,
    moodScore: 88,
    moodLabel: 'Great',
    wordCount: 48,
    isPrivate: false,
    sharedWithTherapist: false,
    aiSummary: null,
    aiFlags: [],
    createdAt: new Date('2026-03-04T19:30:00'),
  },
  {
    id: 'entry_21',
    title: 'February wrap',
    body: `Looking back at the month. More hard days than good ones but I kept writing through most of them. That feels like something. The pattern I'm seeing: I cope better when I move my body, talk to people I actually like, and don't look at my phone before I've been awake for an hour.`,
    moodScore: 66,
    moodLabel: 'Reflective',
    wordCount: 63,
    isPrivate: false,
    sharedWithTherapist: true,
    aiSummary: 'Good self-awareness and pattern recognition. Identified three effective coping mechanisms independently.',
    aiFlags: [],
    createdAt: new Date('2026-03-01T20:45:00'),
  },
]

export const moodOptions = [
  { score: 10, label: 'Awful',      emoji: '😞', color: '#DC2626' },
  { score: 25, label: 'Low',        emoji: '😔', color: '#EA580C' },
  { score: 40, label: 'Anxious',    emoji: '😰', color: '#D97706' },
  { score: 55, label: 'Okay',       emoji: '😐', color: '#CA8A04' },
  { score: 65, label: 'Alright',    emoji: '🙂', color: '#65A30D' },
  { score: 75, label: 'Good',       emoji: '😊', color: '#16A34A' },
  { score: 85, label: 'Great',      emoji: '😁', color: '#0D9488' },
  { score: 95, label: 'Excellent',  emoji: '🤩', color: '#0891B2' },
]

export function moodColor(score: number): string {
  if (score >= 80) return '#1D9E75'
  if (score >= 65) return '#65A30D'
  if (score >= 50) return '#CA8A04'
  if (score >= 35) return '#D97706'
  return '#DC2626'
}

export function formatDate(date: Date): string {
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const days = Math.floor(diff / 86400000)
  if (days === 0) return 'Today'
  if (days === 1) return 'Yesterday'
  if (days < 7)  return `${days} days ago`
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })
}
